section .data
var1 db 10
var2 db 20
var3 db 30
var4 db 40
var5 db 50
var6 db 60
var7 db 70
var8 db 80
var9 db 90
var10 db 100

section .bss
res1 resb 1
res2 resb 1
res3 resb 1
res4 resb 1
res5 resb 1
res6 resb 1
res7 resb 1
res8 resb 1
res9 resb 1
res10 resb 1

section .text
global _start

_start:
    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    xor edi, edi
    syscall

    mov eax, 1
    mov ebx, 2
    mov ecx, 3
    mov edx, 4
    mov esi, 5
    mov edi, 6
    mov ebp, 7
    mov esp, 8
    add eax, ebx
    sub ecx, edx
    imul esi, edi
    xor ebp, esp
    mov [res1], al
    mov [res2], bl
    mov [res3], cl
    mov [res4], dl
    mov [res5], ah
    mov [res6], bh
    mov [res7], ch
    mov [res8], dh
    mov [res9], al
    mov [res10], bl
    mov eax, 60
    syscall 